version: '3'

services:
  
  dev:
    build: ../..
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      - blog
    environment:
      NODE_ENV: development
      SERVER_PORT: 3000
      SERVER_MONGO_URI: mongodb://mongo/node-blog-api
      SERVER_SECRET: devsecret
      ADMIN_PORT: 3001
    volumes:
      - ../../src:/app/src
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    # volumes:
    #   - ../../db:/data/db
    networks:
      - blog

networks:
  blog:
